name = "tictactoe"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-10-29"

[build]
command = "npm run build"
[build.upload]
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [
    { name = "GAMEINSTANCE", class_name = "GameInstance" }
]

[[migrations]]
tag = "v0"
new_classes = ["GameInstance"]